version: "2.1"
services:
  inkyshot:
    build:
      context: ./inkyshot
    privileged: true
    restart: always
    labels:
      io.balena.features.balena-api: "1"
      io.balena.features.supervisor-api: "1"
  # wifi-connect:
  #   build:
  #     context: ./wifi-connect
  #   network_mode: host
  #   privileged: true
  #   restart: on-failure:5
  #   labels:
  #     io.balena.features.dbus: "1"
  #     io.balena.features.firmware: "1"
