name: BalenaCloud Push

on:
  push:
    # Only run workflow for pushes to specific branches
    branches:
      - master

jobs:
  balena-push:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
      - uses: theaccordance/balena-push@v1.0.0
        with:
          api-token: ${{secrets.BALENA_API_TOKEN}}
          application-name: ${{secrets.BALENA_APPLICATION_NAME}}
          application-path: "./balena-wpe"
